expertanalytics/website

- content/about/employees/asmund/index.md
mainly to test some dev tools on ipad
> minor touch-up

- content/services/hpc/index.md
Ragnhild's magic touch, please go easy on it, or @skavhaug is in deep shit...
> Riteration

- content/about/employees/ada/index.md
- content/about/employees/anis/index.md
- content/about/employees/asmund/index.md
- content/about/employees/ata/index.md
- content/about/employees/eigil/index.md
- content/about/employees/eivind/index.md
- content/about/employees/guttorm/index.md
- content/about/employees/johannes/index.md
- content/about/employees/jonathan/index.md
- content/about/employees/martin/index.md
- content/about/employees/ola/index.md
- content/about/employees/pia/index.md
- content/about/employees/rh/index.md
- content/about/employees/robert/index.md
- content/about/employees/stian/index.md
- content/about/employees/trygve/index.md
- content/about/employees/vinzenz/index.md
- content/services/backend/index.md
- content/services/datascience/index.md
- content/services/dataviz/index.md
- content/services/hpc/index.md
- layouts/_default/about.html
- layouts/_default/services.html
This PR makes cross references from services to ppl work.
> Make the cross references work, somehow

- layouts/_default/services.html
- layouts/services/single.html
Improve layout on servicespage
> Add pics to employee listing in services pages

- content/_index.md
- content/projects/shyft.md
> Use markdown in place of html where relevant

- content/about/employees/ola/index.md
- content/services/datascience/index.md
Please expedite this, as `upforgrabs@xal.no` is not a valid email...
> Use separate summary, and add a proper email as contact for DS/ML

- assets/assessment.svg
- assets/css/main.css
- assets/developer_board.svg
- assets/memory.svg
- assets/trending_up.svg
- content/_index.md
- layouts/index.html
- layouts/partials/head.html
To be clear: This should look exactly the same as what we have now.
> Fix markup on front page

- layouts/_default/list.html
- layouts/_default/projects.md
- layouts/posts/list.html
- layouts/training/list.html
> Stop using deprecated Page.URL

- assets/css/main.css
http://center-splash.pr.dev.xal.no/
> Center the front page vertically

- content/services/datascience/_index.md
This is the same as "typos1", but with it's own PR, not as a diff from the makeup branch.
> typo corresction for Service data Science

- content/services/visualization/_index.md
Same as "typos2" but in a fresh branch, not a diff from the makeup branch
> typo corresction for Service Visualization

- .build.yml
Deploy hangs on accepting fingerprint …
> Disable StrictHostKeyChecking for git

- README.md
Minor update on where to find the deployed test branch
> Add information about the deployed branch

- content/about/employees/ada/index.md
The weight property overrides sorting on date.
> Remove weight from ada/index.md

- layouts/about/list.html
- layouts/about/single.html
> Resize images before in build

- layouts/about/list.html
- layouts/projects/taxonomy.html
- layouts/services/taxonomy.html
Forgot to resize these as well in my previous PR.
> Also compress the images in projects and services pages

- content/about/employees/fredrik/index.md
Maskinlæring høres jo kult ut, men vet ikke om jeg tør påstå jeg kan nok ennå til å ta betalt for det!?
> Update services Fredrik

- layouts/training/list.html
They hide important information.
Link to pr build:
http://make-training-pages-better.pr.dev.xal.no/training/
vs
https://expertanalytics.no/training/
> Don't use expandable boxes on training page

- archetypes/default.md
We don't really need drafts with our PR flow.
> Don't default to creating posts in draft mode

- content/about/employees/marty/index.md
- layouts/about/single.html
> Open LinkedIn links in new tab and update to Marty

- content/about/employees/ada/index.md
A little revamping of the About paragraph
> About website

- assets/css/main.css
Not sure if we want dark mode anymore, but we should either fix it or remove the unused css. This PR fixes it.
> Fix dark mode

- content/about/employees/alessandro/index.md
I changed my mind on a couple of details in my description. Here I mention that I have a PhD and I switch to 3rd person
> Do mention that I have a PhD in Physics

- config.toml
Google are moving from UA to GA4
> update google tracker code

- layouts/partials/head.html
This might fix the pipeline issue. It would be very cool if someone would remove me from the website. Thanks :)
> fix action
